# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

# 继承object类，他是Qt所有类的基类，为Qt对象模型的核心(信号槽)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # 窗体大小(宽, 高)、默认坐标为(x=0, y=0)
        MainWindow.resize(621, 593)
        # 主窗体
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # 布局
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_dataFrame = QtWidgets.QLabel(self.centralwidget)
        self.label_dataFrame.setTextFormat(QtCore.Qt.AutoText)
        self.label_dataFrame.setObjectName("label_dataFrame")
        self.verticalLayout_3.addWidget(self.label_dataFrame)
        self.Text_dataFrame = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_dataFrame.setObjectName("Text_dataFrame")
        self.verticalLayout_3.addWidget(self.Text_dataFrame)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        # 按键
        self.Key_Decode = QtWidgets.QPushButton(self.centralwidget)
        self.Key_Decode.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/右箭头.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Key_Decode.setIcon(icon)
        self.Key_Decode.setIconSize(QtCore.QSize(32, 32))
        self.Key_Decode.setCheckable(False)
        self.Key_Decode.setObjectName("Key_Decode")
        self.verticalLayout.addWidget(self.Key_Decode)
        self.Key_Open = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../image/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Key_Open.setIcon(icon1)
        self.Key_Open.setIconSize(QtCore.QSize(32, 32))
        self.Key_Open.setObjectName("Key_Open")
        self.verticalLayout.addWidget(self.Key_Open)
        self.Key_Save = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../image/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Key_Save.setIcon(icon2)
        self.Key_Save.setIconSize(QtCore.QSize(32, 32))
        self.Key_Save.setObjectName("Key_Save")
        self.verticalLayout.addWidget(self.Key_Save)
        self.Key_New = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../image/新建.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Key_New.setIcon(icon3)
        self.Key_New.setIconSize(QtCore.QSize(32, 32))
        self.Key_New.setObjectName("Key_New")
        self.verticalLayout.addWidget(self.Key_New)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_protovalView = QtWidgets.QLabel(self.centralwidget)
        self.label_protovalView.setObjectName("label_protovalView")
        self.verticalLayout_2.addWidget(self.label_protovalView)
        self.Text_ProtocalView = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_ProtocalView.setObjectName("Text_ProtocalView")
        self.verticalLayout_2.addWidget(self.Text_ProtocalView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_history = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_history.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget_history.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dockWidget_history.setAutoFillBackground(False)
        self.dockWidget_history.setObjectName("dockWidget_history")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.treeView_history_2 = QtWidgets.QTreeView(self.dockWidgetContents_2)
        self.treeView_history_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeView_history_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.treeView_history_2.setBaseSize(QtCore.QSize(0, 0))
        self.treeView_history_2.setMouseTracking(False)
        self.treeView_history_2.setTabletTracking(False)
        self.treeView_history_2.setAutoScroll(True)
        self.treeView_history_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.treeView_history_2.setObjectName("treeView_history_2")
        self.verticalLayout_5.addWidget(self.treeView_history_2)
        self.dockWidget_history.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_history)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menu.addAction(self.actionhelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered['bool'].connect(MainWindow.close)
        self.actionNew.triggered['bool'].connect(self.Text_dataFrame.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_dataFrame.setText(_translate("MainWindow", "数据帧"))
        self.Text_dataFrame.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">将数据帧放在这里</p></body></html>"))
        self.Key_Decode.setText(_translate("MainWindow", "解析"))
        self.Key_Decode.setShortcut(_translate("MainWindow", "Ctrl+D, Enter"))
        self.Key_Open.setText(_translate("MainWindow", "打开"))
        self.Key_Save.setText(_translate("MainWindow", "保存"))
        self.Key_New.setText(_translate("MainWindow", "新建"))
        self.label_protovalView.setText(_translate("MainWindow", "解析结果"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuEdit.setTitle(_translate("MainWindow", "编辑"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.dockWidget_history.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.dockWidget_history.setWindowTitle(_translate("MainWindow", "历史记录"))
        self.actionNew.setText(_translate("MainWindow", "新建"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "关闭"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "另存为"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionPrint.setText(_translate("MainWindow", "打印"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionCopy.setText(_translate("MainWindow", "复制"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionCut.setText(_translate("MainWindow", "剪切"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPaste.setText(_translate("MainWindow", "粘贴"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionSelect_All.setText(_translate("MainWindow", "全选"))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionhelp.setText(_translate("MainWindow", "使用说明"))
        self.actionhelp.setShortcut(_translate("MainWindow", "F1"))

